<script src="{{asset('assets/js/jquery-2.0.0.min.js')}}"></script> <!-- Jquery Library Call --> 
<script src="{{asset('assets/plugins/prettyphoto/js/prettyphoto.js')}}"></script> <!-- PrettyPhoto Plugin --> 
<script src="{{asset('assets/js/helper-plugins.js')}}"></script> <!-- Plugins --> 
<script src="{{asset('assets/js/bootstrap.js')}}"></script> <!-- UI --> 
<script src="{{asset('assets/js/waypoints.js')}}"></script> <!-- Waypoints --> 
<script src="{{asset('assets/plugins/mediaelement/mediaelement-and-player.min.js')}}"></script> <!-- MediaElements --> 
<script src="{{asset('assets/js/init.js')}}"></script> <!-- All Scripts --> 
<script src="{{asset('assets/plugins/flexslider/js/jquery.flexslider.js')}}"></script> <!-- FlexSlider --> 
<script src="{{asset('assets/plugins/countdown/js/jquery.countdown.min.js')}}"></script> <!-- Jquery Timer -->